filter:
  dependency_paths:
    - "vendor/"
  excluded_paths:
    - 'test/'

build:
  environment:
    mysql: 5.7
    php:
      pecl_extensions:
        - inotify

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
