/**
 * Removes a page from a functionality.
 *
 * @param p_fun_id The ID of the functionality.
 * @param p_pag_id The ID of the page.
 *
 * @type none
 */
create procedure abc_system_functionality_delete_page
(
  in p_fun_id smallint(5) unsigned, -- type: ABC_AUTH_PAG_FUN.fun_id
  in p_pag_id smallint(5) unsigned --  type: ABC_AUTH_PAG_FUN.pag_id
)
  modifies sql data
begin
  delete
  from ABC_AUTH_PAG_FUN
  where pag_id = p_pag_id
    and fun_id = p_fun_id;
end
