/**
 * Modifies the name a module.
 *
 * @param p_mdl_id The ID of the module.
 * @param p_wrd_id The ID of the word of the name of the module.
 *
 * @type none
 */
create procedure abc_system_module_modify( in p_mdl_id @ABC_AUTH_MODULE.mdl_id%type@,
                                           in p_wrd_id @ABC_AUTH_MODULE.wrd_id%type@ )
modifies sql data
begin
  update ABC_AUTH_MODULE
  set    wrd_id = p_wrd_id
  where  mdl_id = p_mdl_id
  ;
end
