/**
 * Selects all modules.
 *
 * @param p_lan_id The ID of the language used for names.
 *
 * @type rows
 */
create procedure abc_system_module_get_all
(
  in p_lan_id tinyint(3) unsigned -- type: ABC_BABEL_LANGUAGE.lan_id
)
  reads sql data
begin
  select mdl.mdl_id
       , wd1.wdt_text as mdl_name
  from ABC_AUTH_MODULE     mdl
  join ABC_BABEL_WORD_TEXT wd1 on wd1.wrd_id = mdl.wrd_id and --
                                  wd1.lan_id = p_lan_id
  order by mdl_name;
end
