/**
 * Selects all roles in a role group.
 *
 * @param p_rlg_id The ID of the role group.
 *
 * @type rows
 */
create procedure abc_system_role_group_get_roles(in p_rlg_id @aut_role_group.rlg_id%type@)
reads sql data
begin
  select cmp.cmp_id
  ,      cmp.cmp_abbr

  ,      rol.rol_id
  ,      rol.rol_name
  from       AUT_ROLE         rol
  inner join ABC_AUTH_COMPANY cmp  on  cmp.cmp_id = rol.cmp_id
  where rol.rlg_id = p_rlg_id
  order by cmp.cmp_abbr
  ,        rol.rol_weight
  ;
end
