/**
 * Adds a page to a functionality.
 *
 * @param p_fun_id The ID of the functionality.
 * @param p_pag_id The ID of the page.
 *
 * @type none
 */
create procedure abc_system_functionality_insert_page
(
  in p_fun_id smallint(5) unsigned, -- type: ABC_AUTH_PAG_FUN.fun_id
  in p_pag_id smallint(5) unsigned --  type: ABC_AUTH_PAG_FUN.pag_id
)
  modifies sql data
begin
  insert into ABC_AUTH_PAG_FUN( fun_id
                              , pag_id )
  values ( p_fun_id
         , p_pag_id );
end
