/**
 * Selects the password hash of a user account.
 *
 * @param p_cmp_id The ID of the company (safeguard).
 * @param p_usr_id The ID of the user.
 *
 * @type singleton1 varchar
 */
create procedure abc_user_password_get_hash
(
  in p_cmp_id smallint(5) unsigned, -- type: ABC_AUTH_USER.cmp_id
  in p_usr_id int(10) unsigned --      type: ABC_AUTH_USER.usr_id
)
  modifies sql data
begin
  select usr_password_hash
  from ABC_AUTH_USER
  where cmp_id = p_cmp_id
    and usr_id = p_usr_id;
end
