/**
 * Disables a module for a company.
 *
 * @param p_cmp_id The ID of the company.
 * @param p_mdl_id The ID of the module to be disabled.
 *
 * @type none
 */
create procedure abc_company_module_disable( in p_cmp_id @ABC_AUTH_MODULE_company.cmp_id%type@,
                                             in p_mdl_id @ABC_AUTH_MODULE_company.mdl_id%type@ )
modifies sql data
begin
  delete from ABC_AUTH_MODULE_COMPANY
  where cmp_id = p_cmp_id
  and   mdl_id = p_mdl_id
  ;
end
