/**
 * Deletes a company specific page.
 *
 * @param p_cmp_id The ID of the company.
 * @param p_pag_id The ID of the page that must be deleted.
 *
 * @type none
 */
create procedure abc_company_specific_page_delete
(
  in p_cmp_id smallint(5) unsigned, -- type: ABC_AUTH_PAGE_COMPANY.cmp_id
  in p_pag_id smallint(5) unsigned --  type: ABC_AUTH_PAGE_COMPANY.pag_id
)
  modifies sql data
begin
  delete
  from ABC_AUTH_PAGE_COMPANY
  where pag_id = p_pag_id
    and cmp_id = p_cmp_id;
end
